function aiView() {
    const sourceCount=activeAiSources().length;
    const modeItems=[['ask','Ask','sparkles'],['briefs','Briefs','newsletter'],['search','Search','search'],['draft','Draft','edit'],['saved','Saved','bookmark']];
    return `${pageHead('Matanho AI','Practical, permission-aware assistance across your connected work.',`<span class="ai-connected-badge-v16">${icon('lock')} ${sourceCount} sources connected</span><button class="secondary-btn ai-context-mobile-v16" data-action="ai-toggle-context">${icon('services')} Context</button><button class="primary-btn" data-action="ai-new-thread">${icon('plus')} New thread</button>`)}
      <div class="ai-shell-v16 ${state.aiContextOpen?'context-open':''}">
        <aside class="card ai-rail-v16"><nav aria-label="Matanho AI modes">${modeItems.map(x=>`<button class="ai-mode-v16 ${state.aiMode===x[0]?'active':''}" data-ai-mode="${x[0]}">${icon(x[2])}<span>${x[1]}</span></button>`).join('')}</nav><div class="ai-rail-divider-v16"></div><div class="ai-rail-label-v16">Recent</div><div class="ai-rail-recents-v16">${state.aiRecent.slice(0,3).map(x=>`<button data-ai-recent="${x.id}"><span>${esc(x.title)}</span><small>${esc(x.meta)}</small></button>`).join('')}</div><div class="ai-rail-safety-v16">${icon('lock')}<span><strong>Private by design</strong><small>Only uses information you can access.</small></span></div></aside>
        <main class="ai-workspace-v16"><section class="card ai-command-v16"><form id="aiTopForm"><div class="ai-command-icon-v16">${icon('sparkles')}</div><div class="ai-command-field-v16"><label for="aiTopInput">Ask across your work</label><input id="aiTopInput" name="prompt" placeholder="Prepare me for today’s portfolio review" autocomplete="off"/></div><select class="select-control ai-scope-v16" id="aiScope" aria-label="AI search scope"><option ${state.aiScope==='All connected work'?'selected':''}>All connected work</option><option ${state.aiScope==='My work only'?'selected':''}>My work only</option><option ${state.aiScope==='People and knowledge'?'selected':''}>People and knowledge</option></select><button class="primary-btn">${icon('send')} Ask</button></form><div class="ai-prompt-row-v16">${['Summarise my week','Prepare a meeting brief','Draft a project update','Find a colleague'].map(p=>`<button data-ai-prompt="${p}">${icon('sparkles')} ${p}</button>`).join('')}</div></section>${aiModePanel()}</main>
        <aside class="ai-context-v16"><section class="card ai-context-card-v16"><div class="card-title"><div><h3>Active context</h3><p>Choose what Matanho may search for this answer.</p></div><button class="icon-only ai-context-close-v16" data-action="ai-toggle-context" aria-label="Close context">${icon('close')}</button></div><div class="ai-source-list-v16">${aiSources().map(s=>`<button class="ai-source-toggle-v16 ${state.aiContextSources[s.id]!==false?'active':''}" data-ai-source="${s.id}" aria-pressed="${state.aiContextSources[s.id]!==false}"><div class="ai-source-icon-v16">${icon(s.icon)}</div><span><strong>${s.label}</strong><small>${s.detail}</small></span><b>${s.count}</b><i></i></button>`).join('')}</div></section><section class="card ai-context-card-v16"><div class="card-title"><div><h3>Today’s context</h3><p>Useful signals from your workday.</p></div></div><div class="ai-context-signal-v16"><span>${icon('calendar')}</span><div><strong>Portfolio review</strong><small>14:00 · Harare Boardroom</small></div><button data-ai-open-route="calendar">Open</button></div><div class="ai-context-signal-v16"><span>${icon('check')}</span><div><strong>Quarterly LP report</strong><small>High priority · due today</small></div><button data-ai-open-route="my-work">Open</button></div><div class="ai-context-signal-v16"><span>${icon('target')}</span><div><strong>Two decisions need attention</strong><small>Performance and risk thresholds</small></div><button data-ai-open-route="performance">Open</button></div></section><section class="card ai-context-card-v16"><div class="card-title"><div><h3>Related people</h3><p>Available expertise for your current work.</p></div></div>${D.people.slice(0,3).map((p,i)=>`<button class="ai-person-row-v16" data-ai-open-route="people">${avatar(p,colorByIndex(i))}<span><strong>${p.name}</strong><small>${p.role}</small></span><i class="availability-dot ${p.statusType}"></i>${icon('chevron')}</button>`).join('')}</section></aside>
      </div>`;
  }