function myWorkView() {
    const mode=state.workMode||'My work', project=state.workProject||'all', filter=state.workFilter||'All tasks', query=(state.workSearch||'').trim().toLowerCase();
    const projectSource=state.workProjects||D.workProjects;
    const projectStats=projectSource.map(p=>{
      const linked=state.workTasks.filter(t=>t.project===p.name);
      const progress=linked.length?Math.round(linked.reduce((sum,t)=>sum+(t.done?100:Number(t.progress)||0),0)/linked.length):Number(p.progress)||0;
      const open=linked.filter(t=>!t.done).length;
      const status=open&&progress<40?'At risk':progress>=80?'Ahead':'On track';
      return {...p,progress,open,status,linked};
    });
    let tasks=state.workTasks.filter(t=>project==='all'||t.project===project);
    if(filter==='Open') tasks=tasks.filter(t=>!t.done);
    if(filter==='Completed') tasks=tasks.filter(t=>t.done);
    if(filter==='High priority') tasks=tasks.filter(t=>t.status==='High'&&!t.done);
    if(query) tasks=tasks.filter(t=>`${t.title} ${t.project} ${t.owner} ${t.due}`.toLowerCase().includes(query));
    const isToday=t=>String(t.due).toLowerCase().includes('today')||String(t.due).toLowerCase()==='new';
    const groups=[['Due now',tasks.filter(t=>isToday(t)&&!t.done)],['This week',tasks.filter(t=>!isToday(t)&&!t.done)],['Completed',tasks.filter(t=>t.done)]];
    const completion=state.workTasks.length?Math.round(state.workTasks.filter(t=>t.done).length/state.workTasks.length*100):0;
    const avgProgress=state.workTasks.length?Math.round(state.workTasks.reduce((s,t)=>s+(t.done?100:Number(t.progress)||0),0)/state.workTasks.length):0;
    const dueToday=state.workTasks.filter(t=>isToday(t)&&!t.done).length;
    const taskRows=groups.map(([g,list])=>`<section class="dynamic-work-group"><div class="work-group-title"><span>${g}</span><b>${list.length}</b></div>${list.length?list.map(t=>`<article class="work-row dynamic-work-row ${t.done?'is-complete':''}" data-task-open="${t.id}"><button class="check-circle ${t.done?'checked':''}" data-work-toggle="${t.id}" aria-label="${t.done?'Reopen':'Complete'} ${esc(t.title)}">${t.done?icon('check'):''}</button><div class="work-task-title"><strong>${esc(t.title)}</strong><span>${esc(t.project)}</span></div><span class="project-tag">${esc(t.status||'Normal')}</span><span class="work-owner">${esc(t.owner)}</span><span class="work-due">${esc(t.due)}</span><label class="inline-progress" data-stop><span>${t.progress}%</span><select data-work-progress="${t.id}" aria-label="Progress for ${esc(t.title)}">${Array.from({length:11},(_,i)=>i*10).map(v=>`<option value="${v}" ${Number(t.progress)===v?'selected':''}>${v}%</option>`).join('')}</select></label><button class="task-more" data-task-open="${t.id}" aria-label="Open task">${icon('chevron')}</button></article>`).join(''):`<div class="work-empty-state">${icon('check')}<strong>No ${g.toLowerCase()} tasks match this view.</strong><span>Change the filters or add a new task.</span></div>`}</section>`).join('');
    const projectCards=projectStats.map(p=>`<button class="project-card ${project===p.name?'active':''} ${p.status==='At risk'?'at-risk':''}" data-work-project="${esc(p.name)}"><div><strong>${p.name}</strong><span>${p.open} open · ${p.status}</span></div><b>${p.progress}%</b><div class="progress-mini"><i style="width:${p.progress}%"></i></div></button>`).join('');
    const projectsView=`<div class="work-project-board">${projectStats.map((p,i)=>`<article class="card work-project-summary" data-work-project="${esc(p.name)}"><div class="project-summary-icon">${icon(['pie','people','services','news'][i%4])}</div><div><span class="eyebrow">${p.status}</span><h3>${p.name}</h3><p>${p.linked.length} tasks · ${p.linked.filter(t=>t.done).length} complete</p></div><strong>${p.progress}%</strong><div class="progress-bar"><span style="width:${p.progress}%"></span></div><button class="link-btn">Open project ${icon('arrow')}</button></article>`).join('')}</div>`;
    const teamData=[['Investment team',['You','Tawanda Kasere','Rudo Maposa']],['Risk & Compliance',['You','Tawanda Kasere']],['Client Relations',['Nyasha Moyo','Farai Dube']],['Operations',['Farai Dube']]].map(([name,owners],i)=>{const linked=state.workTasks.filter(t=>owners.includes(t.owner));const prog=linked.length?Math.round(linked.reduce((s,t)=>s+(t.done?100:Number(t.progress)||0),0)/linked.length):0;return [name,owners[0],prog,linked.filter(t=>!t.done).length,i]});
    const teamsView=`<div class="work-team-board">${teamData.map(x=>`<article class="card work-team-card">${avatar(D.people[x[4]%D.people.length])}<div><h3>${x[0]}</h3><p>Lead: ${x[1]} · ${x[3]} active tasks</p></div><strong>${x[2]}%</strong><div class="progress-bar"><span style="width:${x[2]}%"></span></div><button class="secondary-btn small-btn">Open team view</button></article>`).join('')}</div>`;
    const roadmapProject=project==='all'?'Southern Africa Expansion':project;
    const roadmapTasks=state.workTasks.filter(t=>t.project===roadmapProject).slice(0,5);
    return `${pageHead('My Work','Turn priorities into measurable progress.',`<select class="select-control" id="workQuarter"><option>Q3 2026</option><option>Q2 2026</option></select><button class="primary-btn" data-action="new-task">${icon('plus')} New task</button>`)}
      <section class="work-metric-strip">${[[state.workTasks.filter(t=>!t.done).length,'Open tasks','check'],[dueToday,'Due today','calendar'],[completion+'%','Completed','target'],[avgProgress+'%','Average progress','performance']].map(x=>`<div class="card work-metric-card"><span>${icon(x[2])}</span><div><strong>${x[0]}</strong><small>${x[1]}</small></div></div>`).join('')}</section>
      <section class="work-command-bar card"><label class="work-search">${icon('search')}<input id="workSearch" value="${esc(state.workSearch||'')}" placeholder="Search tasks, projects or owners…"/></label><select id="workStatusFilter" class="select-control">${['All tasks','Open','Completed','High priority'].map(x=>`<option ${filter===x?'selected':''}>${x}</option>`).join('')}</select><button class="secondary-btn" data-action="clear-work-filters">Clear filters</button><div class="work-live-summary"><span>${state.workTasks.filter(t=>!t.done).length} open</span><strong>${avgProgress}% moving</strong></div></section>
      <div class="work-layout dynamic-work-layout"><aside class="card project-list"><div class="card-title"><h3>Projects</h3><button class="link-btn" data-action="new-project">${icon('plus')}</button></div><button class="project-card project-all ${project==='all'?'active':''}" data-work-project="all"><div><strong>All projects</strong><span>${state.workTasks.filter(t=>!t.done).length} open tasks</span></div><b>${avgProgress}%</b><div class="progress-mini"><i style="width:${avgProgress}%"></i></div></button>${projectCards}<button class="link-btn" style="margin:15px 4px" data-action="clear-work-filters">Reset project filter ${icon('arrow')}</button></aside><main class="card work-table dynamic-work-table"><div class="card-title"><div><h3>${mode}</h3><p>${tasks.filter(x=>!x.done).length} open tasks in this view</p></div><div class="segmented">${['My work','Projects','Teams'].map(x=>`<button class="${mode===x?'active':''}" data-work-mode="${x}">${x}</button>`).join('')}</div></div>${mode==='My work'?taskRows:mode==='Projects'?projectsView:teamsView}</main><aside class="work-side"><section class="card card-pad"><div class="card-title"><h3>Performance connection</h3><button class="link-btn" data-nav="performance">Scorecard</button></div>${[['My goal','Win 12 enterprise accounts',Math.min(100,avgProgress)],['Department objective','Grow enterprise pipeline',Math.min(100,Math.round(avgProgress*.92))],['Company goal','Sustainable growth in core markets',74]].map(x=>`<div class="detail-section"><div style="display:flex;justify-content:space-between"><div><strong style="font-size:10px">${x[0]}</strong><div style="font-size:9px;color:var(--muted);margin-top:3px">${x[1]}</div></div><strong style="font-size:12px">${x[2]}%</strong></div><div class="progress-mini"><i style="width:${x[2]}%"></i></div></div>`).join('')}</section><section class="card card-pad" style="margin-top:14px"><div class="card-title"><h3>Balanced scorecard</h3><span style="font-size:9px;color:var(--muted)">Q3 · Live</span></div><div class="scorecard bsc-mini-scorecard">${[['88','Financial & portfolio'],['92','Stakeholder'],['84','Process & governance'],['86','Learning & growth']].map(x=>`<div class="score-box"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div><button class="secondary-btn" data-action="open-scorecard" style="width:100%;margin-top:12px">Open balanced scorecard</button></section></aside></div>
      <section class="card roadmap dynamic-roadmap"><div class="card-title"><div><h3>${esc(roadmapProject)} roadmap</h3><p>Milestones update immediately as linked tasks move.</p></div><button class="link-btn" data-work-project="${esc(roadmapProject)}">View project ${icon('arrow')}</button></div>${roadmapTasks.length?roadmapTasks.map((t,i)=>`<div class="roadmap-row"><span>${esc(t.title)}</span><div class="timeline"><span style="width:${Math.max(8,Number(t.progress)||0)}%;margin-left:${Math.min(10,i*2)}%">${t.done?'Completed':t.progress>=70?'In review':t.progress>=30?'In progress':'Planned'}</span></div></div>`).join(''):`<div class="work-empty-state"><strong>No linked milestones yet.</strong><span>Add a task to this project to populate the roadmap.</span></div>`}</section>`;
  }