function newsletterEditorView() {
    const canWrite=state.newsletterRole!=='Read only', canPublish=state.newsletterRole==='Publisher';
    if(!canWrite) return `${pageHead('Newsletter Studio','Your current role can read published issues but cannot create or edit content.',`<button class="secondary-btn" data-newsletter-mode="library">Back to newsletters</button>`)}<section class="card restricted-state">${icon('lock')}<h2>Editor access required</h2><p>Ask a Publisher or administrator to grant newsletter authoring access.</p><button class="primary-btn" data-action="request-newsletter-access">Request editor access</button></section>`;
    const panel=state.newsletterStudioPanel||'canvas';
    const blocks=['Cover','Editor’s note','Market outlook','Portfolio signals','People spotlight','Closing'];
    return `${pageHead('Newsletter Studio','Market Brief · July 2026',`<button class="secondary-btn" data-newsletter-mode="library">Exit studio</button><button class="secondary-btn" data-action="preview-newsletter">Preview</button><button class="primary-btn" data-action="share-newsletter">${canPublish?'Share or schedule':'Submit for approval'}</button>`)}
      <div class="editor-mobile-tabs" role="tablist" aria-label="Newsletter studio panels"><button class="${panel==='blocks'?'active':''}" data-editor-panel="blocks">${icon('newsletter')} Blocks</button><button class="${panel==='canvas'?'active':''}" data-editor-panel="canvas">${icon('edit')} Content</button><button class="${panel==='inspector'?'active':''}" data-editor-panel="inspector">${icon('settings')} Publish</button></div>
      <div class="editor-layout editor-layout-v5 responsive-newsletter-studio">
        <aside class="card editor-blocks studio-panel ${panel==='blocks'?'mobile-active':''}" data-studio-panel="blocks"><div class="card-title"><h3>Content blocks</h3><button class="link-btn">Reorder</button></div>${blocks.map((x,i)=>`<button class="block-item ${i===0?'active':''}">${icon(i===0?'cover':'newsletter')}<span>${x}</span><small>${i===0?'Hero':'Content'}</small></button>`).join('')}<button class="secondary-btn" style="width:100%;margin-top:10px">${icon('plus')} Add block</button></aside>
        <main class="card editor-canvas studio-panel ${panel==='canvas'?'mobile-active':''}" data-studio-panel="canvas"><div class="editor-doc"><div class="editor-header-art"><span class="eyebrow">Matanho Intelligence</span><input class="editor-title-input" value="Market Brief" aria-label="Newsletter title"/><p>July 2026 · Market insights, portfolio signals and our view for the month ahead.</p></div><section contenteditable="true"><h2>Editor’s note</h2><p>Welcome to the July edition. This draft can be edited directly, reviewed by colleagues and distributed through controlled audience lists.</p></section><section contenteditable="true"><h2>Market outlook</h2><p>Global markets balanced mixed economic signals in June. Locally, disciplined research and liquidity planning remain central to portfolio decisions.</p></section><section><h2>Portfolio signals</h2><div class="editor-signal-grid"><div><span>Equities</span><strong>45%</strong></div><div><span>Fixed income</span><strong>25%</strong></div><div><span>Private markets</span><strong>30%</strong></div></div></section><section contenteditable="true"><h2>What we are watching</h2><p>Add a concise interpretation of the signals that should shape next month’s decisions.</p></section></div></main>
        <aside class="card editor-inspector studio-panel ${panel==='inspector'?'mobile-active':''}" data-studio-panel="inspector"><div class="card-title"><h3>Distribution & governance</h3><span class="status-pill ${canPublish?'low':'medium'}">${state.newsletterRole}</span></div><label class="form-field"><span>Audience list</span><select class="select-control" id="editorAudience">${state.newsletterLists.map(x=>`<option>${x.name}</option>`).join('')}</select></label><label class="form-field"><span>Subject line</span><input class="input-control" value="Market Brief — July 2026"/></label><label class="form-field"><span>Preheader</span><input class="input-control" value="Portfolio signals and disciplined market perspective."/></label><div class="governance-checks"><div>${icon('check')} Sufficient colour contrast</div><div>${icon('check')} Image descriptions complete</div><div>${icon('check')} Confidential figures checked</div><div>${canPublish?icon('check'):'○'} External publishing permission</div></div><div class="review-thread"><h4>Review comments</h4><div class="mini-comment">${avatar(D.people[0])}<p><strong>Nyasha</strong> Add the ZSE performance note from last week.</p></div><div class="mini-comment">${avatar(D.people[1])}<p><strong>Tawanda</strong> The portfolio positioning section is ready.</p></div><textarea class="textarea-control" placeholder="Add a review comment…"></textarea></div><button class="primary-btn" style="width:100%" data-action="share-newsletter">${canPublish?'Share or schedule':'Submit for approval'}</button></aside>
      </div>`;
  }