function newsLibraryView() {
    const filter=state.newsFilter||'Top stories';
    const filtered=filter==='Top stories'||filter==='For you' ? D.news : D.news.filter(n=>n.category===filter);
    const pool=(filtered.length?filtered:D.news);
    const featured=pool[0], second=pool[1]||D.news[1], third=pool[2]||D.news[2];
    const tabs=['Top stories','Company','Markets','Investment','Technology','Africa','For you'];
    return `${pageHead('News','A curated editorial feed of Matanho updates, investment intelligence and market context.',`<button class="secondary-btn" data-action="personalise-news">${icon('filter')} Personalise feed</button>`)}
      <div class="news-toolbar-premium"><div class="news-tabs">${tabs.map(x=>`<button class="${filter===x?'active':''}" data-news-filter="${x}">${x}</button>`).join('')}</div><div class="news-view-actions"><button class="ghost-btn small-btn">${icon('bookmark')} Saved</button><button class="ghost-btn small-btn">${icon('settings')} Sources</button></div></div>
      <div class="news-layout news-layout-premium"><main><div class="news-feature-grid news-feature-grid-premium">
        ${[featured,second,third].map((n,i)=>`<article class="story-card ${i===0?'featured':''}" data-news-open="${n.id}"><div class="story-art"><img src="${n.image}" alt="${esc(n.title)}" loading="lazy"/></div><div class="story-body"><div class="story-kicker"><span>${n.source}</span><span>${n.category}</span></div><h3>${n.title}</h3><p>${n.excerpt}</p><div class="story-meta"><span>${n.time}</span><span>${n.read} read</span><button class="story-save" data-news-bookmark="${n.id}" aria-label="Save article">${icon(state.newsBookmarks.includes(n.id)?'check':'bookmark')}</button></div></div></article>`).join('')}
      </div><div class="editorial-section-head"><div><span class="eyebrow">Latest intelligence</span><h3>More from your feed</h3></div><button class="link-btn">View all ${icon('arrow')}</button></div><div class="latest-list latest-list-premium">${D.news.filter(n=>![featured.id,second.id,third.id].includes(n.id)).map(n=>`<article class="latest-item" data-news-open="${n.id}"><div class="latest-thumb"><img src="${n.image}" alt="${esc(n.title)}" loading="lazy"/></div><div><div class="story-source">${n.source} · ${n.time}</div><h4>${n.title}</h4><p>${n.excerpt}</p><div class="story-meta"><span>${n.read} read</span><span>${n.category}</span></div></div><button class="story-save" data-news-bookmark="${n.id}" aria-label="Save article">${icon(state.newsBookmarks.includes(n.id)?'check':'bookmark')}</button></article>`).join('')}</div></main>
      <aside><section class="card side-list trending-card"><div class="card-title"><div><span class="eyebrow">Live signal</span><h3>Trending now</h3></div><button class="link-btn">See all</button></div>${D.news.slice(0,5).map((n,i)=>`<div class="rank-row" data-news-open="${n.id}"><div class="rank">0${i+1}</div><div><strong>${n.title}</strong><span>${n.source} · ${n.time}</span></div></div>`).join('')}</section><section class="card side-list market-pulse-card" style="margin-top:14px"><div class="card-title"><div><span class="eyebrow">Market pulse</span><h3>At a glance</h3></div><span class="live-pill"><i></i> Live</span></div>${[['MSCI Frontier','+1.8%','up'],['ZSE All Share','+0.9%','up'],['USD / ZWL','Stable','flat'],['Gold','−0.4%','down']].map(x=>`<div class="market-pulse-row"><span>${x[0]}</span><strong class="${x[2]}">${x[1]}</strong></div>`).join('')}</section><section class="card side-list" style="margin-top:14px"><div class="card-title"><h3>Sources you follow</h3><button class="link-btn">Manage</button></div>${['Matanho Newsroom','Reuters','Bloomberg','TechCabal'].map((source,i)=>`<div class="source-follow-row"><span class="source-mark source-${i}">${source.slice(0,1)}</span><div><strong>${source}</strong><small>${['Company intelligence','Global markets','Institutional finance','African technology'][i]}</small></div><span class="follow-check">${icon('check')}</span></div>`).join('')}</section></aside></div>`;
  }