function profileView() {
    const tab=state.profileTab||'Overview';
    const availabilityClass=state.profileAvailability==='Focus mode'?'focus':state.profileAvailability==='Away'?'away':'';
    const tabs=['Overview','Experience','Goals','Preferences','Documents'];
    const skills=state.profileSkills||[];
    const overview=`<div class="profile-overview-v8 profile-tab-content-v8">
      <div class="profile-column-v8">
        <section class="card info-card"><div class="profile-card-head"><div><h3>About</h3><p>Your professional introduction across Matanho.</p></div><button class="link-btn" data-action="edit-profile">Edit</button></div><p class="profile-about-copy">${esc(state.profile.bio)}</p><div class="profile-meta-row"><span class="profile-meta-chip">${icon('building')} Executive Office</span><span class="profile-meta-chip">${icon('location')} ${esc(state.profile.location)}</span><span class="profile-meta-chip">${icon('clock')} CAT · UTC+2</span></div></section>
        <section class="card info-card"><div class="profile-card-head"><div><h3>Skills and expertise</h3><p>Endorsements from colleagues and project teams.</p></div><button class="link-btn" data-action="add-profile-skill">Add skill</button></div><div class="profile-skill-list">${skills.map((s,i)=>`<button class="profile-skill-chip" data-endorse-skill="${i}" title="Endorse ${esc(s.name)}"><span>${esc(s.name)}</span><b>${s.endorsements}</b></button>`).join('')}</div></section>
        <section class="card info-card"><div class="profile-card-head"><div><h3>Recent contribution</h3><p>Visible outcomes from your current work.</p></div><button class="link-btn" data-nav="performance">View scorecard</button></div><div class="axis-chart-frame">${detailedChartSvg([68,71,73,77,79,84],{xLabels:['Feb','Mar','Apr','May','Jun','Jul'],ySuffix:'%',yLabel:'Contribution score',xLabel:'Month',target:80,ariaLabel:'Monthly contribution score from February to July'})}</div></section>
      </div>
      <div class="profile-column-v8">
        <section class="card info-card"><div class="profile-card-head"><div><h3>Current focus</h3><p>Priority work connected to your goals.</p></div><button class="link-btn" data-nav="my-work">Open My Work</button></div>${[['Zambia Solar Fund II','Financial modelling & due diligence',78],['ESG Integration Framework','Research & policy development',64],['Q3 Portfolio Review','Performance & risk analysis',86]].map((x,i)=>`<button class="profile-focus-item" data-nav="my-work"><div class="task-icon">${icon(['pie','cover','performance'][i])}</div><div><strong>${x[0]}</strong><span>${x[1]}</span></div><b>${x[2]}%</b>${icon('chevron')}</button>`).join('')}</section>
        <section class="card info-card"><div class="profile-card-head"><div><h3>Recognition</h3><p>Recent moments of impact.</p></div><button class="link-btn">View all</button></div>${[['Client Impact Award','Outstanding client insight and institutional impact','Apr 2026'],['Collaboration Champion','Cross-team support and knowledge sharing','Feb 2026'],['Quality Distinction','High-confidence portfolio analysis','Dec 2025']].map((x,i)=>`<div class="feedback-item"><div class="task-icon">${icon(i===1?'people':'target')}</div><div><strong style="font-size:10px">${x[0]}</strong><p>${x[1]}</p></div><span style="font-size:8px;color:var(--muted);margin-left:auto">${x[2]}</span></div>`).join('')}</section>
      </div>
      <aside class="profile-column-v8">
        <section class="card info-card"><div class="profile-card-head"><div><h3>This week</h3><p>Your visible work pattern.</p></div><button class="link-btn" data-nav="calendar">Calendar</button></div><div class="profile-week-v8">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((x,i)=>`<div class="profile-week-day ${i===3?'today':''}"><span>${x}</span><strong>${27+i}</strong><i style="background:${i<4?'#0ca66f':i===4?'#176ee4':'#c5cfda'}"></i></div>`).join('')}</div></section>
        <section class="card info-card"><div class="profile-card-head"><div><h3>Organisation path</h3><p>Your position in the Matanho structure.</p></div></div>${[['Matanho Investment Management','Joined May 2022'],['Managing Partner','Current role'],['Executive Office','Current team']].map((x,i)=>`<div class="detail-line"><i class="status-dot ${i===0?'available':'meeting'}"></i><div><strong>${x[0]}</strong><div style="font-size:9px;color:var(--muted)">${x[1]}</div></div></div>`).join('')}</section>
        <section class="card info-card"><div class="profile-card-head"><div><h3>Personal shortcuts</h3><p>Frequently used employee services.</p></div></div><div class="service-grid">${[['Payslips','wallet','payroll'],['Leave balance','calendar','leave'],['Benefits','services','payroll'],['Learning','learning','learning']].map(x=>`<button class="service-card card" data-service="${x[2]}"><div class="task-icon">${icon(x[1])}</div><div><h4>${x[0]}</h4></div></button>`).join('')}</div></section>
      </aside>
    </div>`;
    const experience=`<div class="profile-tab-content-v8 profile-overview-v8"><section class="card info-card" style="grid-column:span 2"><div class="profile-card-head"><div><h3>Career experience</h3><p>A structured history of roles, responsibilities and outcomes.</p></div><button class="secondary-btn small-btn" data-action="edit-profile">Update experience</button></div><div class="profile-timeline">${[['Managing Partner','Matanho Investment Management','May 2022 — Present','Leading institutional strategy, operating model design and enterprise investment-management transformation.'],['Director, Investment Strategy','Kuvamba Capital Partners','Jan 2019 — Apr 2022','Built portfolio research, investment committee governance and client reporting systems.'],['Senior Investment Analyst','Southern Cross Advisory','Jun 2015 — Dec 2018','Led financial modelling, due diligence and multi-sector investment research.']].map(x=>`<article class="profile-timeline-item"><h3>${x[0]}</h3><span>${x[1]} · ${x[2]}</span><p>${x[3]}</p></article>`).join('')}</div></section><aside class="profile-column-v8"><section class="card info-card"><div class="profile-card-head"><div><h3>Education</h3><p>Verified academic record.</p></div></div>${[['MSc Finance','University of London','2015'],['BSc Computer Science','University of Zimbabwe','2012']].map(x=>`<div class="detail-line">${icon('learning')}<div><strong>${x[0]}</strong><div style="font-size:9px;color:var(--muted)">${x[1]} · ${x[2]}</div></div></div>`).join('')}</section><section class="card info-card"><div class="profile-card-head"><div><h3>Professional credentials</h3><p>Current certifications and memberships.</p></div></div>${[['CFA Institute','Investment Foundations'],['Institute of Directors Zimbabwe','Member'],['Microsoft','Power BI Data Analyst']].map(x=>`<div class="detail-line">${icon('check')}<div><strong>${x[0]}</strong><div style="font-size:9px;color:var(--muted)">${x[1]}</div></div></div>`).join('')}</section></aside></div>`;
    const goals=`<div class="profile-tab-content-v8"><div class="profile-card-head"><div><h3>My aligned goals</h3><p>Personal objectives connected to department and company outcomes.</p></div><button class="primary-btn" data-nav="performance">Open full scorecard</button></div><div class="profile-goal-grid">${[['Lead and close the Zambia renewable-energy mandate',78,'40% weight','High confidence'],['Diversify the sector research pipeline',65,'25% weight','Medium confidence'],['Build client-insights capability',72,'20% weight','High confidence'],['Increase team knowledge sharing',60,'15% weight','Medium confidence']].map((x,i)=>`<article class="card profile-goal-card"><div class="profile-goal-head"><h3>${x[0]}</h3><span>${x[1]}%</span></div><p>${['Final recommendation and investment committee pack in progress.','Three priority sector briefs underway with two external experts.','New insight templates are being used across client reporting.','Monthly renewable-energy knowledge sessions are active.'][i]}</p><div class="progress-bar"><span style="width:${x[1]}%"></span></div><div class="profile-goal-meta"><span>${x[2]}</span><span>${x[3]}</span></div><button class="link-btn" data-nav="performance" style="margin-top:12px">Open goal ${icon('arrow')}</button></article>`).join('')}</div><section class="card info-card" style="margin-top:14px"><div class="profile-card-head"><div><h3>Goal-progress trend</h3><p>Weighted completion across the current review cycle.</p></div><span class="live-pill"><i></i> Live scorecard</span></div><div class="axis-chart-frame">${detailedChartSvg([52,58,61,66,69,74,78],{xLabels:['Jan','Feb','Mar','Apr','May','Jun','Jul'],ySuffix:'%',yLabel:'Weighted goal progress',xLabel:'Month',target:75,ariaLabel:'Weighted goal progress by month'})}</div></section></div>`;
    const prefs=state.profilePreferences;
    const preferences=`<div class="profile-tab-content-v8"><div class="profile-card-head"><div><h3>Work and visibility preferences</h3><p>Control how colleagues coordinate with you and what profile information they can see.</p></div><button class="primary-btn" data-action="edit-profile-preferences">Edit preferences</button></div><div class="profile-preferences-grid"><section class="card preference-card-v8"><h3>Work pattern</h3>${[['Focus hours',prefs.focusHours],['Preferred contact',prefs.preferredContact],['Office days',prefs.officeDays],['Timezone',prefs.timezone]].map(x=>`<div class="preference-value"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</section><section class="card preference-card-v8"><h3>Profile visibility</h3>${[['Show availability',prefs.showAvailability],['Share skills and endorsements',prefs.shareSkills],['Show current projects',prefs.showProjects],['Allow profile discovery',prefs.discoverable]].map(x=>`<div class="preference-value"><span>${x[0]}</span><strong style="color:${x[1]?'var(--success)':'var(--muted)'}">${x[1]?'Enabled':'Disabled'}</strong></div>`).join('')}<button class="link-btn" data-action="edit-profile-preferences" style="margin-top:10px">Manage visibility</button></section><section class="card preference-card-v8"><h3>Communication</h3>${[['Digest frequency','Daily'],['Meeting buffer','10 minutes'],['Auto-decline focus time','Enabled'],['Working location sharing','Team only']].map(x=>`<div class="preference-value"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</section><section class="card preference-card-v8"><h3>Privacy overview</h3><p class="profile-about-copy">Your employee profile is visible within Matanho. Sensitive HR, payroll and personal documents remain permission-restricted.</p><div class="governance-notice" style="margin-top:12px">${icon('lock')} Permission checks apply to every profile field and document.</div></section></div></div>`;
    const documents=`<div class="profile-tab-content-v8"><div class="profile-doc-toolbar"><div><h3 style="margin:0">My documents</h3><p style="font-size:9px;color:var(--muted);margin:5px 0 0">Secure employee records, certificates and profile attachments.</p></div><div class="page-actions"><button class="secondary-btn" data-nav="services">Employee records</button><button class="primary-btn" data-action="upload-profile-document">${icon('plus')} Upload document</button></div></div><section class="card info-card"><div class="profile-document-list">${state.profileDocuments.map((d,i)=>`<button class="profile-document-row" data-profile-document="${i}"><div class="profile-file-icon">${icon(d.icon||'newsletter')}</div><div><strong>${esc(d.name)}</strong><span>${esc(d.category)} · ${esc(d.size)}</span></div><span class="profile-doc-type status-pill ${d.status==='Verified'?'low':'blue'}">${esc(d.status)}</span><span class="profile-doc-date">${esc(d.updated)}</span><span class="profile-doc-actions">${icon('chevron')}</span></button>`).join('')}</div></section></div>`;
    const content={Overview:overview,Experience:experience,Goals:goals,Preferences:preferences,Documents:documents}[tab]||overview;
    return `${pageHead('My Profile','Manage how you appear, work and connect across Matanho.',`<button class="secondary-btn" data-action="copy-profile">Preview profile</button><button class="primary-btn" data-action="edit-profile">${icon('edit')} Edit profile</button>`)}<div class="profile-page profile-page-v8"><section class="card profile-banner profile-banner-v8"><div class="profile-portrait-wrap">${avatar(D.user,'blue')}<button class="profile-photo-action" data-action="change-profile-photo" title="Update profile photo">${icon('edit')}</button></div><div class="profile-banner-copy"><span class="verified-pill">${icon('check')} Verified profile</span><h2>${esc(state.profile.name)}</h2><p>${esc(state.profile.role)}</p><div class="profile-meta-row"><span class="profile-meta-chip">${icon('newsletter')} ${esc(state.profile.email)}</span><span class="profile-meta-chip">${icon('location')} ${esc(state.profile.location)}</span><span class="profile-meta-chip">${icon('profile')} Reports to Chipo Dube</span></div></div><div class="profile-banner-controls"><button class="availability-control ${availabilityClass}" data-action="toggle-profile-availability"><i></i><div><strong>${esc(state.profileAvailability)}</strong><span>Click to change your visible status</span></div>${icon('down')}</button><div class="profile-completion-v8"><div><span>Profile completeness</span><span>8 of 9 sections</span></div><div class="progress-bar"><span style="width:92%"></span></div><strong>92%</strong></div></div></section><nav class="profile-tabs profile-tabs-v8" aria-label="Profile sections">${tabs.map(x=>`<button class="${tab===x?'active':''}" data-profile-tab="${x}">${x}</button>`).join('')}</nav>${content}</div>`;
  }