/** Fund Cash Ledger — screenshot-aligned mock */

export const ledgerTransactions = [
  {
    date: '27 May 2025',
    fund: 'Zambezi Growth Fund I',
    cashAccount: 'ZAM Operating · USD',
    bank: 'CBZ Custody',
    type: 'Receipt' as const,
    description: 'Capital call receipt · INV-0007',
    debit: '—',
    credit: '2,150,000.00',
    balance: '28,745,132.40',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '27 May 2025',
    fund: 'Nyaradzo Pension Fund',
    cashAccount: 'NPF Operating · ZWL',
    bank: 'CBZ Bank',
    type: 'Payment' as const,
    description: 'Broker settlement · ECO.ZW',
    debit: '845,220.00',
    credit: '—',
    balance: '12,884,220.00',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '26 May 2025',
    fund: 'Mbare Equity Mandate',
    cashAccount: 'MBE Settlement · USD',
    bank: 'Stanbic Custody',
    type: 'Transfer' as const,
    description: 'Internal transfer to fee account',
    debit: '125,000.00',
    credit: '—',
    balance: '8,410,550.18',
    currency: 'USD',
    approval: 'Pending' as const,
  },
  {
    date: '26 May 2025',
    fund: 'Victoria Falls Fund',
    cashAccount: 'VFF Operating · USD',
    bank: 'CBZ Custody',
    type: 'Receipt' as const,
    description: 'Dividend receipt · DLTA.ZW',
    debit: '—',
    credit: '245,870.00',
    balance: '15,420,880.12',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '26 May 2025',
    fund: 'Hunyani Opportunities',
    cashAccount: 'HUN Broker · USD',
    bank: 'IH Securities',
    type: 'Payment' as const,
    description: 'Management fee accrual cash',
    debit: '187,500.00',
    credit: '—',
    balance: '6,114,220.00',
    currency: 'USD',
    approval: 'Pending' as const,
  },
  {
    date: '25 May 2025',
    fund: 'Zambezi Growth Fund I',
    cashAccount: 'ZAM Operating · USD',
    bank: 'CBZ Custody',
    type: 'Payment' as const,
    description: 'Distribution to LP · INV-0012',
    debit: '980,000.00',
    credit: '—',
    balance: '26,595,132.40',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '25 May 2025',
    fund: 'Nyaradzo Pension Fund',
    cashAccount: 'NPF Operating · ZWL',
    bank: 'CBZ Bank',
    type: 'Receipt' as const,
    description: 'Unit deal inflow',
    debit: '—',
    credit: '1,200,000.00',
    balance: '13,729,440.00',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '24 May 2025',
    fund: 'Mbare Equity Mandate',
    cashAccount: 'MBE Settlement · USD',
    bank: 'Stanbic Custody',
    type: 'Transfer' as const,
    description: 'FX settlement leg USD',
    debit: '50,000.00',
    credit: '—',
    balance: '8,535,550.18',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '24 May 2025',
    fund: 'Victoria Falls Fund',
    cashAccount: 'VFF Operating · USD',
    bank: 'CBZ Custody',
    type: 'Payment' as const,
    description: 'Custody fee',
    debit: '18,400.00',
    credit: '—',
    balance: '15,175,010.12',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '23 May 2025',
    fund: 'Hunyani Opportunities',
    cashAccount: 'HUN Broker · USD',
    bank: 'IH Securities',
    type: 'Receipt' as const,
    description: 'Subscription proceeds',
    debit: '—',
    credit: '750,000.00',
    balance: '6,301,720.00',
    currency: 'USD',
    approval: 'Pending' as const,
  },
]

/** Trading Cash Ledger rows — client trading accounts */
export const tradingLedgerTransactions = [
  {
    date: '27 May 2025',
    client: 'Zambezi Asset Management',
    account: 'ZAM-001-001',
    cashAccount: 'Custody cash · USD',
    bank: 'Stanbic Custody',
    type: 'Receipt' as const,
    description: 'Trade settlement buy · ECO.ZW',
    debit: '—',
    credit: '124,530.21',
    balance: '1,284,563.20',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '27 May 2025',
    client: 'Nyaradzo Pension Fund',
    account: 'NPF-OP-ZWL',
    cashAccount: 'Operating · ZWL',
    bank: 'CBZ Bank',
    type: 'Payment' as const,
    description: 'Broker commission',
    debit: '18,420.00',
    credit: '—',
    balance: '228,734,561.32',
    currency: 'ZWL',
    approval: 'Approved' as const,
  },
  {
    date: '26 May 2025',
    client: 'Sunrise Equity Mandate',
    account: 'SUN-001-USD',
    cashAccount: 'Broker settlement · USD',
    bank: 'IH Securities',
    type: 'Payment' as const,
    description: 'Buy settlement TRD-SETTLE-8841',
    debit: '3,005.00',
    credit: '—',
    balance: '6,995.00',
    currency: 'USD',
    approval: 'Pending' as const,
  },
  {
    date: '26 May 2025',
    client: 'Eastern Africa Mandate',
    account: 'EAM-022-USD',
    cashAccount: 'Custody cash · USD',
    bank: 'CBZ Custody',
    type: 'Receipt' as const,
    description: 'Dividend receipt · DLTA.ZW',
    debit: '—',
    credit: '41,200.00',
    balance: '842,110.55',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '25 May 2025',
    client: 'Omnibus Client Pool',
    account: 'OMN-CBZ-USD',
    cashAccount: 'Omnibus · USD',
    bank: 'CBZ Custody',
    type: 'Transfer' as const,
    description: 'Reservation release · settle window',
    debit: '—',
    credit: '75,000.00',
    balance: '1,147,887.65',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '25 May 2025',
    client: 'Zambezi Asset Management',
    account: 'ZAM-001-001',
    cashAccount: 'Custody cash · USD',
    bank: 'Stanbic Custody',
    type: 'Payment' as const,
    description: 'Custody fee May 2025',
    debit: '2,450.00',
    credit: '—',
    balance: '1,160,032.99',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '24 May 2025',
    client: 'Sunrise Equity Mandate',
    account: 'SUN-001-USD',
    cashAccount: 'Broker settlement · USD',
    bank: 'Stanbic Custody',
    type: 'Receipt' as const,
    description: 'Client funding receipt',
    debit: '—',
    credit: '10,000.00',
    balance: '10,000.00',
    currency: 'USD',
    approval: 'Approved' as const,
  },
  {
    date: '24 May 2025',
    client: 'Nyaradzo Pension Fund',
    account: 'NPF-OP-ZWL',
    cashAccount: 'Operating · ZWL',
    bank: 'CBZ Bank',
    type: 'Payment' as const,
    description: 'Bank charges',
    debit: '1,245.00',
    credit: '—',
    balance: '228,488,691.32',
    currency: 'ZWL',
    approval: 'Pending' as const,
  },
]

export const monthlyCashTrend = [
  { month: 'Nov 2024', zambezi: 23, mbare: 6, victoria: 14, hunyani: 2 },
  { month: 'Dec 2024', zambezi: 27, mbare: 8, victoria: 19, hunyani: 3 },
  { month: 'Jan 2025', zambezi: 29, mbare: 11, victoria: 18, hunyani: 4 },
  { month: 'Feb 2025', zambezi: 32, mbare: 12, victoria: 20, hunyani: 4 },
  { month: 'Mar 2025', zambezi: 26, mbare: 10, victoria: 16, hunyani: 3 },
  { month: 'Apr 2025', zambezi: 26, mbare: 8, victoria: 14, hunyani: 2 },
  { month: 'May 2025', zambezi: 30, mbare: 10, victoria: 19, hunyani: 2 },
]

export const monthlyCashTrendSeries = [
  { key: 'zambezi', name: 'Zambezi Growth Fund I', color: '#3B82F6' },
  { key: 'mbare', name: 'Mbare Ventures Fund', color: '#10B981' },
  { key: 'victoria', name: 'Victoria Falls Infrastructure Fund', color: '#A855F7' },
  { key: 'hunyani', name: 'Hunyani Private Equity Fund', color: '#F59E0B' },
] as const


export const cashByFund = [
  { name: 'Zambezi Growth Fund I', value: 59.85, pct: 46.6, color: '#3B82F6' },
  { name: 'Mbare Equity Mandate', value: 28.12, pct: 21.9, color: '#10B981' },
  { name: 'Victoria Falls Fund', value: 22.4, pct: 17.4, color: '#A855F7' },
  { name: 'Hunyani Opportunities', value: 18.09, pct: 14.1, color: '#F59E0B' },
]
