/** Accounting V2 design tokens — PDF locked palette. No green. */
export const ac = {
  navy: "#0B1739",
  navySoft: "#14244F",
  cobalt: "#2563EB",
  cobaltSoft: "#DBEAFE",
  paleSky: "#D8E8FF",
  canvas: "#F5F8FC",
  card: "#FFFFFF",
  border: "#E5E7EB",
  borderStrong: "#D1D5DB",
  text: "#0B1739",
  textMuted: "#6B7280",
  textFaint: "#9CA3AF",
  pending: "#F59E0B",
  pendingSoft: "#FEF3C7",
  exception: "#DC2626",
  exceptionSoft: "#FEE2E2",
  posted: "#2563EB",
  postedSoft: "#DBEAFE",
  radius: 8,
  radiusSm: 6,
  radiusPill: 999,
} as const
