/** Design tokens sampled from PDF screenshots (pages 4–13 white/purple set). */
export const pm = {
  primary: "#7C3AED",
  primaryHover: "#6D28D9",
  primarySoft: "#F5F3FF",
  primaryBorder: "#DDD6FE",
  bg: "#F9FAFB",
  card: "#FFFFFF",
  border: "#E5E7EB",
  text: "#111827",
  textMuted: "#6B7280",
  textSecondary: "#475569",
  success: "#10B981",
  successSoft: "#D1FAE5",
  successText: "#065F46",
  warning: "#F59E0B",
  warningSoft: "#FEF3C7",
  warningText: "#92400E",
  danger: "#EF4444",
  dangerSoft: "#FEE2E2",
  dangerText: "#991B1B",
  info: "#3B82F6",
  infoSoft: "#DBEAFE",
  /** Page 3 portfolio dashboard accents */
  blue: "#2563EB",
  blueSoft: "#EFF6FF",
  radius: "0.75rem",
  radiusSm: "0.5rem",
  /** Density scale for mock screens */
  pagePad: "p-4 lg:p-5",
  sectionGap: "space-y-4",
  titleSize: "text-xl",
  controlH: "h-8",
} as const
